steps:
  count: 30
  delay: 1000

hotel: 
  elevator:
    capacity: 3
    quantity: 2
  crazy-elevator:
    stationary-probability: 1/3
    skip-destination-probability: 1/3
    normal-behaviour-probability: 1/3
    deny-unloading-probability: 1/2
    quantity: 1
  floors:
    number: 4
  spawn-probability:
    ground: 0.65
    other: 0.35
  display:
    column-width:
      floor: 5
      elevator: 24
      persons: 20
